### ISSUE TITLE
Is there an option to lock the rearranged Blizzard Frames

### ISSUE THREAD

**Issue by Bantscho** [Azilroka/ProjectAzilroka#10]
Hello,

I'm using the ElvUI Edit BENIKUI in combination with:

1. [Location Plus for ElvUI]
2. [ElvUI Nuts and Bolts] and
3. [ProjectAziroka]

In the ElvUI Settings is MovableFrame enabled and everything works as expected, but is there an option to lock the new position of these blizzard frames like the character window or the world map?

**Comment by Repooc** [comment]
No there isnt
