### ISSUE TITLE
Moving Minimap Button Bar

### ISSUE THREAD

**Issue by kenn213** [Azilroka/ProjectAzilroka#17]
I'm trying to move the minimap button bar location on the screen, but I'm unable to find the way. I'm not using Elv or Tuk, just this add-on as a standalone.

PS: Love this add-on and the functionality it brings. Thanks for the hard work.

**Comment by stamarty** [comment]
I was also having this issue, and tried using 'MoveAnything' addon to move the squareminimapbuttonbar, but nothing seems to work. I looked through the code and it seems you can only move the frame if you have tukui or elvui installed? I really hope that isn't the case as those two addons, while great, make my computer load incredibly slowly.

**Comment by NyLan-1** [comment]
Same issue, trying to figure out how to move the minibar without Elvui..

**Comment by Azilroka** [comment]
Pretty sure you just click and drag the whole bar.

**Comment by bigjman1978** [comment]
Did anyone else get this to work?

**Comment by flow0284** [comment]
Even without any other addon installed/activated i am not able to move the bar.

**Comment by Diagonet** [comment]
Having this issue too, hopefully not ElvUI exclusive
