### ISSUE TITLE
QuestSounds does not work

### ISSUE THREAD

**Issue by Fyler74** [Azilroka/ProjectAzilroka#2]
There is no sound to be heard.
After / console scriptErrors 1
do i I get this error message:

Message: ...rface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:56: attempt to call field 'ReadyForTurnIn' (a nil value)
Time: Mon May 31 19:02:04 2021
Count: 27
Stack: ...rface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:56: attempt to call field 'ReadyForTurnIn' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `ReadyForTurnIn'
[string "@Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua"]:56: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: errMsg = "...rface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:56: attempt to call field 'ReadyForTurnIn' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by sererinn** [comment]
Sounds stopped working for me in both Classic Era and TBC. 
Getting this from the log:
`Message: ...rface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:56: attempt to call field 'ReadyForTurnIn' (a nil value)
Time: Mon May 31 21:55:50 2021
Count: 2
Stack: ...rface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:56: attempt to call field 'ReadyForTurnIn' (a nil value)
[string "@Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua"]:56: in function `?'
[string "@Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <...jectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 SetQuest = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:26
 Enable = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 QuestID = 8346
 IsPlaying = false
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 GetOptions = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:137
 PlaySoundFile = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:35
 ObjectivesComplete = 0
 name = "ProjectAzilroka_QuestSounds"
 Initialize = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:181
 IsEnabled = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 Authors = "Azilroka"
 ObjectivesTotal = 0
 Description = "Audio for Quest Progress & Completions."
 baseName = "ProjectAzilroka"
 RegisterMessage = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 BuildProfile = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:165
 RegisterSounds = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:92
 QUEST_WATCH_UPDATE = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:88
 GetName = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 NewModule = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 IsModule = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\ProjectAzilroka\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 CountCompletedObjectives = <function> defined @Interface\AddOns\ProjectAzilroka\Modules\QuestSounds.lua:14
 Credits = "Yoco"
 SetEnabledState = <function> defined @Interface\AddOns\ProjectAzilroka\Li`

**Comment by dblanch369** [comment]
I too am getting this lua error every time I compete the requirements for a quest, instead of the sound.
