### ISSUE TITLE
Addon doesnt load in retail on 1.83

### ISSUE THREAD

**Issue by g-dove** [Azilroka/ProjectAzilroka#20]
Just updated 1.83 on retail and wow no longer recognises the addon, if I back version to 1.82 it works fine again though

**Comment by Azilroka** [comment]
Then you installed it wrong

**Comment by maphex** [comment]
I have the same issue i had to revert to 1.82 also and it works fine

**Comment by g-dove** [comment]
> I have the same issue i had to revert to 1.82 also and it works fine

Does it work if you restart the game after updating, or updating while the game is not running? 

The package changes in 1.83 mean that the retail (mainline) .TOC file has been removed, so it should fallback to the default .TOC file, but if the addon has been loaded with the mainline TOC and then you take it away (eg. by updating) then it seems like the game won't use the fallback until it's been restarted, regardless if you reload, change characters etc.

Just a bit of info about the changes and why I think this is happening, hopefully a little more useful than "you installed it wrong" 😂
