### ISSUE TITLE
Quest Sounds

### ISSUE THREAD

**Issue by WilliamTalafuse** [Azilroka/ProjectAzilroka#21]
When I complete a quest or quest objective, the objective progress sound is played regardless of quest progress.  I am unable to get the quest complete or quest objective complete sounds to play at all.

**Comment by realrobd** [comment]
Yea the whole quest sounds thing is wonky and needs adjustment.

**Comment by Azilroka** [comment]
If I remember right this was always an issue in WotLK.. I'll have to see about fixing it while leveling
