### ISSUE TITLE
Square Minimap Buttons: Other addons and items randomly jumping into buttons

### ISSUE THREAD

**Issue by bchevreau** [Azilroka/ProjectAzilroka#27]
Hi !

Thanks for all the great work on ProjectAzilroka. Wanted to give a bit of feedback although I assume you guys already noticed.

Subcategory: Square Minimap Buttons

Issue(s): 
- Group Finder "eye" icon sometimes jumping into one of the buttons
- Tomtom uncleared waypoints sometimes randomly jumping into buttons (showing multiple waypoint icons as buttons)
- Narcissus icon jumping in and out of buttons on reload and back to top left corner of the minimap (also breaking their layout selector when inside a button)
- Covenant panel jumping back into minimap with large size sometimes
- Mail icon disappearing completely from both minimap and buttons

**Comment by MalikiOne** [comment]
Pretty much same issue. Keep getting extra empty minimap buttons showing up.

**Comment by bchevreau** [comment]
Most of those issues were fixed, thanks a lot Azilroka! Any chance we could have a bit more control over what pops out of the addon than the 5 Blizzard options? In particular Narcisus layou on their icon minimap is probably gonna be a mess for you to figure out how to fix, and could deserve being left on the minimap as a quick fix

![image](https://user-images.githubusercontent.com/12772470/201337931-492d6e79-7cc6-4f1f-8be6-9f91423d5491.png)
