### ISSUE TITLE
ReputationRewards overlap other rewards

### ISSUE THREAD

**Issue by Haymz** [Azilroka/ProjectAzilroka#34]
![ReputationRewards_Disabled](https://user-images.githubusercontent.com/31546289/203157442-a013785a-35a4-4034-8f86-a9e9fdff79ff.png)
![ReputationRewards_Enabled](https://user-images.githubusercontent.com/31546289/203157449-10dac478-c0a5-4db5-8594-7e171ea4b292.png)

Images attached to display issue. Image attached with feature disabled for reference

**Comment by Azilroka** [comment]
Yea its been broken for awhile.. They keep changing the names of the anchors.
