### ISSUE TITLE
[WotLk] Problems with Questlinks / Questie

### ISSUE THREAD

**Issue by Isilrond** [Azilroka/ProjectAzilroka#39]
i opened a ticket on the github page of questie and found out that ProjectAzilroka is the real problem, here is the link with some screenshots and LUA error text

https://github.com/Questie/Questie/issues/4408

**Comment by Azilroka** [comment]
That has nothing to do with ProjectAzilroka.

ProjectAzilroka does not replace the chat output behavior of the Default Chat Frame.
