### ISSUE TITLE
LUA Issue

### ISSUE THREAD

**Issue by OscarBlue13** [Azilroka/ProjectAzilroka#47]
Hey,

i've got an issue when i move my mouse over my aura:

Here my issue-text:

Message: ...ce/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:100: attempt to index field 'backdrop' (a nil value)
Time: Mon Feb 27 17:41:19 2023
Count: 1
Stack: ...ce/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:100: attempt to index field 'backdrop' (a nil value)
[string "@Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua"]:162: in function `UpdateAuras'
[string "@Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua"]:194: in function `?'
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 UpdateAuras = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:157
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 EnableModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 GetOptions = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:200
 Holder = MouseoverAurasHolder {
 }
 name = "ProjectAzilroka_MouseoverAuras"
 Initialize = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:230
 IsEnabled = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 Authors = "Azilroka"
 CustomFilter = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:51
 Description = "Auren für Dein Mouseover Ziel"
 BuildProfile = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:217
 RegisterMessage = <function> defined @Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 CreateAuraIcon = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:24
 FilterIcons = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:130
 SetPosition = <function> defined @Interface/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:110
 baseName = "ProjectAzilroka"
 UpdateSettings = <function> defined @Interface/AddOns/Proje

Message: ...ce/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:100: attempt to index field 'backdrop' (a nil value)
Time: Mon Feb 27 17:41:20 2023
Count: 22
Stack: ...ce/AddOns/ProjectAzilroka/Modules/MouseoverAuras.lua:100: attempt to index field 'backdrop' (a nil value)

Locals: 

I've no glue how to repair ist ;-(

Thanks for help:
Oscar

**Comment by G0ldheart** [comment]
Same error too.  I am using the current release versions as of 3/5/23 of ElvUI, Merathilis, and BenikUI.  Disabling mouse over auras "fixes" of course.

**Comment by Reavolt** [comment]
Faced the same error using the current version of the addon and BenikUI
