### ISSUE TITLE
Movable Frames -> Resets position

### ISSUE THREAD

**Issue by Hollicsh** [Azilroka/ProjectAzilroka#49]
After moving the frames, when re-opening, they reset their location.
Is it possible to make the position of the frames not reset and remain in place ?

As an example:
![Screenshot_2](https://user-images.githubusercontent.com/54585769/236169430-edd13162-ab48-4617-9cc1-3a9df226041f.png)

**Comment by Azilroka** [comment]
I removed that code awhile back.

**Comment by Hollicsh** [comment]
It would be very convenient for the frames to remain in the positions they were moved to.
This is especially true for the map frame.

**Comment by Hollicsh** [comment]
Okay, Sir. Thank you !
