### ISSUE TITLE
Square minimap buttons not working on all addon buttons

### ISSUE THREAD

**Issue by branpg** [Azilroka/ProjectAzilroka#53]
Hello, 

Few days ago I updated elvui and Addon compartment appeared and I noticed some of those icons isn't showing up into the Square minimap buttons box. Also AllTheThings icon started appearing over the minimap instead of in the box (Previously it worked).
![image](https://github.com/Azilroka/ProjectAzilroka/assets/25660904/aa2268d9-ec0b-4e2c-acb3-f80b35c52df1)
List of buttons not showing up:
-ElvUI
-Infinite Raid Tools
-Protoform Synthesis Field Journal
-SimulationCraft

I`m curious about how the addon works and if it would be possible to implement a config panel to choose what buttons show. Before I deep dive into the addon code I would like to know your opinion about it. In case I recibe a positive response I will create a branch and make a PR.

Thanks in advance.

**Comment by Azilroka** [comment]
All The Things should be in the button bar again (in the alpha at least). The ones that are added into the addon compartment are not gathered.

**Comment by branpg** [comment]
Some of the ones gathered into the addon compartment are also gathered there. From the 9 addons being gathered by addon compartment 5 are also into the square. I can give you examples of the addons appearing on both places if it's of any help.

**Comment by Azilroka** [comment]
You could sure. However the way my addon works would actually remove them from the addon compartment.. The newer addons may have an option to turn off the minimap icon and leave the one in the addon compartment as it really isn't a button gathering one but is a drop down.

**Comment by Azilroka** [comment]
To use the addon compartment you have to do the following

Add to the toc
```
## AddonCompartmentFunc: ElvUI_AddonCompartmentFunc

```

Add a function which is above referenced
```
do
	function E:AddonCompartmentFunc()
		E:ToggleOptions()
	end

	_G.ElvUI_AddonCompartmentFunc = E.AddonCompartmentFunc
end

```

None of which deals with the minimap buttons on the map.

**Comment by branpg** [comment]
Thanks for the help, I get how does it works now. Also installing alfa works for ATT.
