### ISSUE TITLE
ReputationRewards no longer a feature?

### ISSUE THREAD

**Issue by Matheney2k** [Azilroka/ProjectAzilroka#57]
I loved the feature, but for some reason it no longer exists? I may have missed it, but I checked the changelogs and did not see any mention of it being removed, but for whatever reason I cannot get it to load up for me. I have tried uninstalling/reinstalling, but to no avail. Any help would be greatly appreciated!
![noreps](https://github.com/Azilroka/ProjectAzilroka/assets/144171543/3e53ffc5-bebc-4e6a-b451-f5567998568a)

**Comment by dblanch369** [comment]
I loved and miss this feature too, any chance it will come back?

**Comment by Azilroka** [comment]
It's currently disabled
