### ISSUE TITLE
Square Minimap Bar broken since yesterdays update

### ISSUE THREAD

**Issue by vderaa** [Azilroka/ProjectAzilroka#6]
Hey!  Since yesterdays update, the Square Minimap Bar is no longer keeping scaling correctly.
Image attached.

Cheers :)

![image](https://user-images.githubusercontent.com/67520782/144887771-15c60292-a75f-4c37-a30a-a11fa98e6ebe.png)

**Comment by Repooc** [comment]
There wasnt any updates yesterday, the current release is still 1.77... I would suggest to try the alpha build

**Comment by vderaa** [comment]
Many Thanks; upgrading to Alpha worked :)
