### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by NoIdeaTBH** [Azilroka/ProjectAzilroka#63]
When I open the friends list or guild list on both SoD and hardcore classic, I got this error :

Message: ...dOns/ProjectAzilroka/Modules/EnhancedFriendsList.lua:80: attempt to call method 'SetGradientAlpha' (a nil value)
Time: Tue Dec  5 11:31:30 2023
Count: 11
Stack: ...dOns/ProjectAzilroka/Modules/EnhancedFriendsList.lua:80: attempt to call method 'SetGradientAlpha' (a nil value)
[string "=[C]"]: in function `SetGradientAlpha'
[string "@Interface/AddOns/ProjectAzilroka/Modules/EnhancedFriendsList.lua"]:80: in function `SetGradientColor'
[string "@Interface/AddOns/ProjectAzilroka/Modules/EnhancedFriendsList.lua"]:203: in function <...dOns/ProjectAzilroka/Modules/EnhancedFriendsList.lua:108>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `FriendsFrame_UpdateFriendButton'
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:1137: in function `FriendsFrame_UpdateFriends'
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:530: in function `FriendsList_Update'
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:273: in function <Interface/FrameXML/FriendsFrame_Shared.lua:272>
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2160: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2005: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1873: in function <Interface_Vanilla/FrameXML/UIParent.lua:1869>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2652: in function `ShowUIPanel'
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:962: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by RLaneo** [comment]
You can temporarily resolve this by making the following changes:

1 - Open:
C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\ProjectAzilroka\Modules (or whatever your path is)

2 - Open EnhancedFriendsList.lua

3 - Search for lines 79-82 and delete them:
	```else
		button.Left:SetGradient("Horizontal", color1, color2)
		button.Right:SetGradient("Horizontal", color2, color1)```
