### ISSUE TITLE
LUA error after the 10.2.6 patch

### ISSUE THREAD

**Issue by reuzii** [Azilroka/ProjectAzilroka#66]
20x ...Ons/ProjectAzilroka/Modules/SquareMinimapButtons.lua:186: attempt to index field 'Tracking' (a nil value)
[string "@ProjectAzilroka/Modules/SquareMinimapButtons.lua"]:186: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 EnableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:409
 RawHookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:394
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 Authors = "Azilroka    Sinaris    Omega    Durc"
 RegisterMessage = <function> defined @BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Update = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:385
 IsHooked = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:492
 db = <table> {
 }
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 RegisterEvent = <function> defined @BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 IterateModules = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 Title = "|cFF16C3F2Square|r |cFFFFFFFFMinimap Buttons|r"
 RawHook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:312
 isEnabled = true
 Bar = SquareMinimapButtonBar {
 }
 UnlockButton = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:84
 Enable = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 GetModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:172
 HandleBlizzardButtons = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:98
 ScheduleRepeatingTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:129
 Buttons = <table> {
 }
 GetName = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 GetOptions = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:460
 RemoveTexture = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:63
 Initialize = <function> defined @ProjectAzilroka/Modules/SquareMinimapButtons.lua:528
 orderedModules = <table> {
 }
 Disable = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 Description = "Minimap Button Bar / Minimap Button Skinning"
 HookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:365
 Hider = Frame {
 }
 baseName = "ProjectAzilroka"
 IsModule = <function> defined @Interface

**Comment by ChrisKader** [comment]
It seems any references to `_G.MinimapCluster.Tracking` need to be updated to `_G.MinimapCluster.TrackingFrame`.

**Comment by reuzii** [comment]
> It seems any references to `_G.MinimapCluster.Tracking` need to be updated to `_G.MinimapCluster.TrackingFrame`.

works like a charm, thank you.
