### ISSUE TITLE
square minimap buttons

### ISSUE THREAD

**Issue by cyberbook78** [Azilroka/ProjectAzilroka#72]
Message: ...Ons/ProjectAzilroka/Modules/SquareMinimapButtons.lua:186: attempt to index field 'Tracking' (a nil value)
Time: Mon Jul 22 10:37:42 2024
Count: 1
Stack: ...Ons/ProjectAzilroka/Modules/SquareMinimapButtons.lua:186: attempt to index field 'Tracking' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ProjectAzilroka/Modules/SquareMinimapButtons.lua"]:186: in function `?'
[string "@Interface/AddOns/AlterEgo/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...e/AddOns/AlterEgo/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by bobbycvi** [comment]
i fixed this issue, but i'm unable to create a PR over here (or create a branch with the fix).
