### ISSUE TITLE
LUA-error when Mouseover items, NPC, etc.

### ISSUE THREAD

**Issue by ishirra** [Azilroka/ProjectAzilroka#79]
When mousing over NPC's or items, I get following LUA error.  The count runs up rapidly when you keep your mouse on top of the NPC/item:

817x ...ceProjectAzilroka/Modules/MouseoverAuras.lua:172: attempt to call upvalue 'GetMouseFocus' (a nil value)
[string "@ProjectAzilroka/Modules/MouseoverAuras.lua"]:172: in function <...ceProjectAzilroka/Modules/MouseoverAuras.lua:171>

Locals:
self = MouseoverAurasHolder {
 1 = MouseoverAurasHolderButton1 {
 }
 elapsed = 0
 anchoredIcons = 1
 createdIcons = 1
}
elapsed = 0.239000
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetMouseFocus' (a nil value)"
GetMouseFocus = nil
MA = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 Holder = MouseoverAurasHolder {
 }
 name = "ProjectAzilroka_MouseoverAuras"
 orderedModules = <table> {
 }
 Authors = "Azilroka"
 Description = "Auras for your mouseover target"
 baseName = "ProjectAzilroka"
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 Title = "|cFF16C3F2Mouseover|r|cFFFFFFFFAuras|r"
 isEnabled = true
 moduleName = "MouseoverAuras"
}

**Comment by ChrisKader** [comment]
The issue is `GetMouseFocus` has been replaced by `GetMouseFoci`.

**Comment by ChrisKader** [comment]
Also, `GetMouseFoci()` returns a table now.

**Comment by Repooc** [comment]
He is aware of the change in GetMouseFocus, thanks though, he is slowly getting around to updating his addons
