### ISSUE TITLE
Moving collections frame can cause frame to become unresponsive.

### ISSUE THREAD

**Issue by jacarn2157** [Azilroka/ProjectAzilroka#8]
Clicking and dragging the top part of the frame in line with where the frame's title is causes the frame to become glitched and unresponsive happens with all tabs in the collections frame.

the moved frame can have two states of glitched from what i can tell based on which direction the frame is moved
1) frame become unresponsive but does not have a glitched visual state
2) frame becomes unresponsive and has a glitched visual state.

i have attached an image of the glitched state as well as the elvui status

![2022-01-21 15_13_34-World of Warcraft](https://user-images.githubusercontent.com/98187371/150594889-fa9268c5-486f-4776-8a47-4412fe9ab046.png)
![2022-01-21 15_08_53-World of Warcraft](https://user-images.githubusercontent.com/98187371/150594928-3fd1c820-c13f-4d15-979d-2f46660a9719.png)

**Comment by Azilroka** [comment]
That's why it has been removed from the movable portion.
