### ISSUE TITLE
stAddonManager

### ISSUE THREAD

**Issue by WaRRiorF13** [Azilroka/ProjectAzilroka#80]
Are the Addon Profiles broken and not coming back or is there still more being done?

**Comment by Azilroka** [comment]
It should work as of the latest commit

**Comment by Azilroka** [comment]
Ill be checking it tomorrow when I get off work.

**Comment by WaRRiorF13** [comment]
![Addon Menu](https://github.com/user-attachments/assets/eddf981f-d830-4b79-a3cf-13ae3ca0b1cf)

I'll reinstall, but this is all I see.

**Comment by Azilroka** [comment]
That isn't stAddonManager

**Comment by WaRRiorF13** [comment]
Is that not what used to load the Addon Profiles on the right of my addon menu?

**Comment by Azilroka** [comment]
No, that one is Blizzard's that you shown.

**Comment by WaRRiorF13** [comment]
Oh, I know. The widget isn’t overriding the Blizz one like it used to even though I have it on.

**Comment by WaRRiorF13** [comment]
That’s the issue I’m having.

**Comment by Azilroka** [comment]
You need to be on the alpha branch on Wago / Curseforge

**Comment by WaRRiorF13** [comment]
Ok, I’ll give that a shot after work.

**Comment by Roxatha** [comment]
![image](https://github.com/user-attachments/assets/224b0df2-dd0c-4c9d-89e4-fd00a627bcb5)

I have the last alpha and it still shows the blizzard one.

**Comment by WaRRiorF13** [comment]
I updated to the Alpha build and I have the same issue. It's not showing the addon loadouts I had saved before.

**Comment by Roxatha** [comment]
> I updated to the Alpha build and I have the same issue. It's not showing the addon loadouts I had saved before.

by anychance are u trying to use the + in the left corner of the chat? or using the esc--> Addons?
Cause mine works using esc-->Addons...the + in the corner aint working anymore and i think is a benkui/elvui thing

**Comment by WaRRiorF13** [comment]
I am using the main game menu. I actually don’t know what + you’re talking about.

**Comment by Roxatha** [comment]
> I am using the main game menu. I actually don’t know what + you’re talking about.

![image](https://github.com/user-attachments/assets/b7adfd81-526c-4ac0-8d0f-0bde9159101b)
 u see the + in the left down corner...that + :p

And by any chance did u put any other addon manager addon? cause i desinstall all addons and reinstall  1 by 1 and a addon manager was blocking the esc--< addon to work as usual...

**Comment by WaRRiorF13** [comment]
Well, I definitely don’t have that plus on my UI.

As far as addon managers, I only have the one so unless ElvUI has something blocking it, I don’t know.

**Comment by WaRRiorF13** [comment]
Can confirm now that I'm home. Unloading all the addons doesn't fix it.

**Comment by Azilroka** [comment]
Its because you are on releases and not alpha. You would have to right click it in your addon manager and go to release type and select alpha for it to update so it works.

**Comment by WaRRiorF13** [comment]
I am on the Alpha builds, it's still not working

**Comment by WaRRiorF13** [comment]
> I updated to the Alpha build and I have the same issue. It's not showing the addon loadouts I had saved before.

**Comment by WaRRiorF13** [comment]
I'm sad this never resolved :(
