### ISSUE TITLE
[Cata]ProjectAzilroka doesn't load

### ISSUE THREAD

**Issue by cyaphis** [Azilroka/ProjectAzilroka#84]
Just a weird issue that ProjectAzilroka does not load on my Mage, but it's all good on all other chars even I tried to create a new Mage it works. Elvui 13.74 and ProjectAzilroka updated on 15/08.

I tried remove cache/WTF/interface, and it doesn't work. I don't know if it is related that I did a faction transfer for this Mage days ago. Any ideas thanks!

**Comment by Azilroka** [comment]
Most likely because you are frost on the one mage with a pet. Pets are broken in the addon at the moment.

**Comment by cyaphis** [comment]
Thanks for the reply, not sure what's the pet frozen issue lol. I'll wait for updates then.

**Comment by kyriana** [comment]
i have 2 Firespecc´s and the same issue.
i allrdy installed 1.87 and it works perfect.

**Comment by cyaphis** [comment]
Just wanna ask how can I find 1.87? It seems only one 1.88 version on CurseForge for Cata.

**Comment by kyriana** [comment]
https://www.curseforge.com/wow/addons/projectazilroka/files/4381426

**Comment by cyaphis** [comment]
Thanks for the help. It seems not work for me :(

**Comment by cyaphis** [comment]
Yeah I do use the zip file

**Comment by cyaphis** [comment]
My issue is fixed after today's update thanks!
