### ISSUE TITLE
Project Azilroka Button gone in ElvUI Settings window

### ISSUE THREAD

**Issue by JeanCodeVanDamme** [Azilroka/ProjectAzilroka#85]
Since I came back to retail I am missing the Project Azilroka Button on the bottom left in the ElvUI Settings window. 
Did I miss something, got it moved to another location? It is installed and activated but I can't find its menu anywhere.

**Comment by Repooc** [comment]
release build is not supported in retail (which was released last year in may), use the dev/alpha build of it which u can get using a client like wowup

**Comment by chucktheviking** [comment]
How do you get the dev/alpha build? I'm looking everywhere in the repository, and not seeing anything but Main branch. I know how to add it to wowup once I can figure out where it is here.

**Comment by Azilroka** [comment]
It's main

**Comment by Azilroka** [comment]
It's main

**Comment by chucktheviking** [comment]
Okay, I guess how do you select the Alpha build in WoWup as when you put in the github url to install, you get 1.88 released a year ago. 
![image](https://github.com/user-attachments/assets/9a5635cd-2a3b-4cae-a708-da7637c76868)

**Comment by Repooc** [comment]
Just use wowup-cf or wago version (u may need to enable the wago support if u are using that version of the wowup client). Don't do the add via GitHub... Just search for it in GetAddOns section and select the alpha version there

**Comment by chucktheviking** [comment]
Ahh, I was looking for those versions on Github. Didn't realize they were primarily on curseforge.
