### ISSUE TITLE
Latest alpha broke Square Minimap buttons...

### ISSUE THREAD

**Issue by dblanch369** [Azilroka/ProjectAzilroka#86]
Just FYI, updated two latest alpha this morning and now Square Minimap Buttons is gone lol.

I rolled back to the previous alpha from yesterday and it works.  So it was something in the latest one.

**Comment by Ra1dMaX** [comment]
thanks, did the rollback myself. heck the main reason i run this plugin was because they removed the square minimap button frame from S&L plugin

**Comment by dblanch369** [comment]
now fixed in latest... closing.....
