### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by gottshy** [Azilroka/ProjectAzilroka#89]
Hey, are these issues something from my side in terms of a different addon or from the addon itself?
https://imgur.com/DWXH3F2

Greetings Nils

**Comment by Azilroka** [comment]
Are you cloning the repo? If so that's why.

**Comment by gottshy** [comment]
sorry for not having the knowledge but what exactly do you mean and how can i fix it?

**Comment by gottshy** [comment]
oh i got it^^ cheers and sorry for the inconvenience
