### ISSUE TITLE
Cannot seem to get addon to load with ElvUI

### ISSUE THREAD

**Issue by KingJerbear** [Azilroka/ProjectAzilroka#90]
The addon is enabled, according to some searching I've done, settings should be accessed through the main ElvUI options panel but nothing is showing up. It's showing normally in my Curseforge, shows as loaded in my Wow addons list, and I am not getting any errors. Is there a slash command I'm supposed to be using or something? Any help is much appreciated

![image](https://github.com/user-attachments/assets/ce3f6eee-f961-4113-8648-ca7e317d7078)

**Comment by billyknit** [comment]
Same
