### ISSUE TITLE
102x ProjectAzilroka/Cooldowns.lua:366: attempt to index global 'E' (a nil value)

### ISSUE THREAD

**Issue by Sakatard** [Azilroka/ProjectAzilroka#96]
102x ProjectAzilroka/Cooldowns.lua:366: attempt to index global 'E' (a nil value)
[string "@ProjectAzilroka/Cooldowns.lua"]:366: in function `UpdateCooldownSettings'
[string "@ProjectAzilroka/Cooldowns.lua"]:385: in function `UpdateCooldownSettings'
[string "@ProjectAzilroka/Init.lua"]:632: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 ScanSpellBook = <function> defined @ProjectAzilroka/Init.lua:483
 GetTimeInfo = <function> defined @ProjectAzilroka/Cooldowns.lua:41
 GetUIScale = <function> defined @ProjectAzilroka/Init.lua:148
 GrowthDirection = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 Cooldown_TextThreshold = <function> defined @ProjectAzilroka/Cooldowns.lua:75
 TBC = false
 LC = <table> {
 }
 AS = <table> {
 }
 CopyTable = <function> defined @ProjectAzilroka/Init.lua:280
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 GetSpellCharges = <function> defined @ProjectAzilroka/Init.lua:386
 Classes = <table> {
 }
 MyFaction = "Horde"
 SetTemplate = <function> defined @ProjectAzilroka/Init.lua:233
 Cooldown_Options = <function> defined @ProjectAzilroka/Cooldowns.lua:180
 PLAYER_LOGIN = <function> defined @ProjectAzilroka/Init.lua:616
 BuildProfile = <function> defined @ProjectAzilroka/Init.lua:583
 Cooldown_UnbuggedTime = <function> defined @ProjectAzilroka/Cooldowns.lua:67
 ShortValue = <function> defined @ProjectAzilroka/Init.lua:173
 UIScale = 0.900000
 db = <table> {
 }
 QuestSounds = <table> {
 }
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Options = <table> {
 }
 GetSpellCooldown = <function> defined @ProjectAzilroka/Init.lua:376
 OnSetCooldown = <function> defined @ProjectAzilroka/Cooldowns.lua:262
 iFilger = <table> {
 }
 Version = "1.91"
 Noop = <function> defined @ProjectAzilroka/Init.lua:51
 Cooldown_TimerUpdate = <function> defined @ProjectAzilroka/Cooldowns.lua:171
 NewModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 Locale = "enUS"
 Cooldown_BelowScale = <function> defined @ProjectAzilroka/Cooldowns.lua:81
 TimeIndicatorColors = <table> {
 }
 ScanTooltip = PAScanTooltip {
 }
 IsAddOnPartiallyEnabled = <function> defined @ProjectAzilroka/Init.lua:85
 GetOptions = <function> defined @ProjectAzilroka/Init.lua:579
 name = "ProjectAzilroka"
 Disable = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 Defaults = <table> {
 }
 ToggleBlizzardCooldownText = <function> defined @ProjectAzilroka/Cooldowns.lua:305
 AllPoints = <table> {
 }
 Print = <function> defined @ProjectAzilroka/Init.lua:169
 OzCD = <table> {
 }
 EnhancedPetBattleUI = <table> {
 }
 RegisterCooldown = <function> defined @ProjectAzilroka/Cooldowns.lua:290
 Clamp = <function> defined @ProjectAzilroka/Init.lua:183
 RGBToHex = <function> defined @ProjectAzilroka/Init.lua:188
 MouseoverAuras = <table> {
 }
 Solid = "Interface\Buttons\WHITE8X8"
 UnregisterEvent = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 SetDefaultModuleLibraries = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Tukui = false
 SLE = false
 AddOnSkins = true
 Cooldown_TimerEnabled = <function> defined @ProjectAzilroka/Cooldowns.lua:159
 EnableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 baseName = "ProjectAzilroka"
 IterateEmbeds = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 PetBattleFrameHider = PA_PetBattleFrameHider {
 }
 MyRealm = "Arugal"
 Cooldown_TimerStop = <function> defined @ProjectAzilroka/Cooldowns.lua:176
 RegisteredCooldowns = <table> {
 }
 Printf = <function> defined @Inte
 
 
![image](https://github.com/user-attachments/assets/10e36906-b319-432d-828c-c80c0d12849c)

**Comment by Sakatard** [comment]
Have experienced this issue for over a month now, thought it might fix itself with the recent pushes on git but still hasn't and don't see any other issues being posted about it so I thought I'd go ahead and do so.

The square minimap plugin doesn't work also which I'm assuming is because of the addon getting stuck at the cooldown text one.

**Comment by Azilroka** [comment]
You probably have the release or on the wrong alpha.. You just need to reinstall it.
