### ISSUE TITLE
stAddonManager - feature request

### ISSUE THREAD

**Issue by maslevich** [Azilroka/ProjectAzilroka#97]
It would be nice to show a game version for an addon from addon toc file in a tooltip when mouseover.

**Comment by maslevich** [comment]
No no. I mean when you open a dialogue window with add-ons and put your
mouse over any of checkbox of any addon there is a tool tip in which you
can see a small information about it, for example it's a requirements or
its version. And I suggest to put in this tooltip information about off
version of the client version to which this add on is developed from a toc
file.

Best wishes,
Artyom

**Comment by Azilroka** [comment]
You mean the Interface version?

**Comment by maslevich** [comment]
Yes, that's it. ))

Best wishes,
Artyom

**Comment by Azilroka** [comment]
Also the Interface field is a non query which I can't pull.
